Mobile first design
migcm06/portfolio1.2 pull request #1
Opened 2023-07-05 19:14 UTC by migcm06

Now I've coded the navbar with the logo and menu.

I have also started to code the presentation part.

2023-07-05 22:02 UTC, DuaneDave requested changes
Hi @migcm06  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ You styled the app really great
✔️ Your HTML is really semantic

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 22:02 UTC, DuaneDave commented on index.html
> +        </div>
Good job Setting up your project with the correct semantic tags. To make your code even more semantic, I recommend using an unordered list `ul` to render the social links since they are actually a list of links.

HINT: Do not forget to still use an `a` tag even inside of the `li` tag

2023-07-05 22:02 UTC, DuaneDave commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Consider changing this from `This project is [MIT](./LICENSE) licensed.` to `This project is [MIT](./MIT.md) licensed` in order to correctly link to your license file for this project so that your repo will be even more professional

2023-07-05 22:02 UTC, DuaneDave commented on index.html
> +        </div>
Consider representing the logo of your page as a link using the `a` tag in order to improve the overall page accessibility

2023-07-05 22:02 UTC, DuaneDave commented on index.html
> +          </div>
I recommend that you use the `nav` tag as a wrapper for the hamburger menu for better semantics and for correct markup structuring

2023-07-06 05:57 UTC, migcm06 commented on index.html
> +          </div>
Thanks, you're so professional.

2023-07-06 06:07 UTC, Efiamotu-1 approved these changes
Hi @migcm06 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR Title & summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 06:07 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] please kindly work on your design for the social media icons so that it matches the provided figma design as shown below. It is important that your design closely matches the provided figma template as this shows your attention to details as a frontend developer :+1: :sparkles: 
- figma design
 ![op](https://github.com/migcm06/portfolio1.2/assets/89055502/b342822d-164d-4076-ba5d-aa8e4cef51a8)
- your design
![oyp](https://github.com/migcm06/portfolio1.2/assets/89055502/76b3e90b-5622-4756-8c1a-52cc7a19fc9a)

2023-07-06 06:15 UTC, migcm06 commented on index.html
Thanks !

2023-07-06 06:16 UTC, merged