I have finished the conctar form section for the portfolio exercise
migcm06/portfolio1.2 pull request #3
Opened 2023-07-11 16:52 UTC by migcm06

* I have created the contact form section. 

*This section has a functional contact form, and at the end, there are images with links to social media.

2023-07-11 23:14 UTC, rica213 requested changes
# 🟡 STATUS: REQUIRED CHANGES ♻️ 
Hi Miguel, 
I'm happy to review your code again 🥰

The functionality of your form is working as intended ✅ 
However, I want you to fix some design before moving on to the next milestone 👍🏽 
Kindly check them in the comment section below 👇🏽 

<img src="https://media4.giphy.com/media/fOFKxYBjX631aHRBjW/giphy.gif"/>

Happy coding!

## Highlights

Good Design ✔️
Professional Documentation ✔️
No Linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

# Cheers, and Happy coding 🖥️

## If anything is not 100% clear, kindly mention me in your comment and I will reply ASAP 🤞

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 23:14 UTC, rica213 commented on index.html
> +            </form>
Kindly stick to the Figma design as much as possible, because it will help you enhance your paying attention to details skill. Furthermore, having a beautiful design will help you stand out 😁 
- [ ] Please add more padding on your inputs 📍 
- [ ] Please reduce the vertical spacing between the name input and the email input ❇️ 

Your design 👇🏽 

![Screenshot from 2023-07-12 01-50-26](https://github.com/migcm06/portfolio1.2/assets/10439283/b74a196d-8c8e-4455-ac09-c8d0b43b8bc4)

Design from figma 👇🏽 

![Screenshot from 2023-07-12 01-59-15](https://github.com/migcm06/portfolio1.2/assets/10439283/b7901ba8-1990-4784-a1e1-a56109d18fe2)

2023-07-11 23:14 UTC, rica213 commented on styles.css
> +}
- [ ] Kindly implement the button interaction 🅱️ It will enhance the accessibility of your application ♿

2023-07-11 23:14 UTC, rica213 commented on index.html
> +    </footer>
- [ ] Kindly add a line before and after the social links, as the Figma design provides 📘 Note that sticking to the design is important, it will ensure you have a beautiful website 😊 

Your design 👇🏽 

![Screenshot from 2023-07-12 01-47-33](https://github.com/migcm06/portfolio1.2/assets/10439283/3bbc3f45-7eb4-4db8-b875-f33fcefbb92a)

Design from Figma 👇🏽 

![Screenshot from 2023-07-12 01-47-48](https://github.com/migcm06/portfolio1.2/assets/10439283/593ecf72-5d12-4f2a-a9a1-a5aca9746b0e)

2023-07-12 12:39 UTC, migcm06 commented on index.html
> +            </form>
Ready!

2023-07-12 12:48 UTC, migcm06 commented on styles.css
> +}
Thanks, I forgot this part.

2023-07-12 13:00 UTC, migcm06 commented on index.html
> +    </footer>
Thank you again, you're so pro tell me how to make that changes.

2023-07-12 13:11 UTC, V-Blaze approved these changes
Hi @migcm06  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- UI looks great💯
-  Excellent communication with the reviewer👍
-  Clean organized code🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 13:16 UTC, merged

2023-07-12 13:17 UTC, rica213 commented on index.html
> +    </footer>
@migcm06 
Hi Miguel, one possibility is to use the `<hr>` tag, and you can set the following rules to your CSS 👍🏽 to replicate the second line

```
border: 3px solid #090808;
border-radius: 2px;
width: 25%;
margin: 0 auto;
```

Feel free to adjust the value based on the Figma design 😉  Good luck 💯