I have designed the Desktop portfolio version
migcm06/portfolio1.2 pull request #4
Opened 2023-07-13 19:47 UTC by migcm06

* On this occasion, I used queries to implement the changes for larger screens.
* I have changed some background images and styles too.

2023-07-14 23:59 UTC, zieeco requested changes
Hi @migcm06,

<img height="220" src="https://media0.giphy.com/media/ehxq3SFXUxvtK2qDFs/giphy.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice using media query. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 23:59 UTC, zieeco commented on styles.css
> +
- Hey, please, let's kindly fix the placement of these headers to be aligned correctly with the tags as seen in the images below to improve your design:


*your design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/594cbc8f-d445-4e96-a637-9a2c5a0fa4f0)

*Figma design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/f7998c26-eb9d-4248-bfea-9c2511ba620c)

2023-07-14 23:59 UTC, zieeco commented on styles.css
> +  }
- Hi, please try to reduce the margin-bottom as this is making your design have too much space at the bottom making your design not consistent as compared to the original design:

*your design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/3543438b-bef4-4274-8c35-4b158336dd68)


*Figma design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/365b658e-568e-47ed-bc96-7e88274ea4aa)

2023-07-14 23:59 UTC, zieeco commented on styles.css
> +  }
- Hey, let's also control the space at the bottom of the header here to improve our design. the space here is too much compared to the original design.

*Figma design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/d7a08c89-94ac-4f79-907a-4ff0daa0b2b1)


*Your design*
![image](https://github.com/migcm06/portfolio1.2/assets/59397159/f688a631-5a4b-4167-a8dd-431df3e8a6b6)

2023-07-16 01:06 UTC, Lizdev-05 approved these changes
Hi @migcm06 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights

:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-16 01:13 UTC, merged